### ISSUE TITLE
環境変数の設定がうまくいっていない

### ISSUE THREAD

**Issue by 618knot** [frontend-conference-hokkaido-2024/landing-page-2024#58]

**Comment by 618knot** [comment]
twitterの共有用に持つ本番環境のURLや、forteeのapiのurlを環境変数として持っている。(とくに、apiのURLは隠蔽目的)
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/blob/5d7ab45e085176f6cfeeb45e98e7e4858f64949d/src/components/EventSummary.tsx#L40
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/blob/5d7ab45e085176f6cfeeb45e98e7e4858f64949d/.env.local.sample#L4
- nextjs.ymlに環境変数についての記述
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/blob/5d7ab45e085176f6cfeeb45e98e7e4858f64949d/.github/workflows/nextjs.yml#L62

- environments -> github-pages -> Environment secretsに、`FORTEE_API_HOST`と`PRODUCTION_URL`の2つを登録

上記二つの対応を行ったが、本番環境から確認しても`https://twitter.com/intent/tweet?hashtags=frontendo&url=`となっている。つまり、`PRODUCTION_URL`を取得できていないということになる。

環境変数をとってこれないとforteeのapiを叩くことができないので、環境変数は取得できるようにしたい。

**Comment by 618knot** [comment]
```yml
      - name: Build project
        run: |
          echo "REACT_APP_API_URL=$API_URL" > .env
          npm run build
```
